<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.5.57">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>arima</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { display: inline-block; text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="ARIMA_files/libs/clipboard/clipboard.min.js"></script>
<script src="ARIMA_files/libs/quarto-html/quarto.js"></script>
<script src="ARIMA_files/libs/quarto-html/popper.min.js"></script>
<script src="ARIMA_files/libs/quarto-html/tippy.umd.min.js"></script>
<script src="ARIMA_files/libs/quarto-html/anchor.min.js"></script>
<link href="ARIMA_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="ARIMA_files/libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="ARIMA_files/libs/bootstrap/bootstrap.min.js"></script>
<link href="ARIMA_files/libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="ARIMA_files/libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">


</head>

<body class="fullcontent">

<div id="quarto-content" class="page-columns page-rows-contents page-layout-article">

<main class="content" id="quarto-document-content">




<div class="cell">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="cf">if</span> (<span class="sc">!</span><span class="fu">requireNamespace</span>(<span class="st">"lmtest"</span>, <span class="at">quietly =</span> <span class="cn">TRUE</span>)) <span class="fu">install.packages</span>(<span class="st">"lmtest"</span>)</span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="cf">if</span> (<span class="sc">!</span><span class="fu">requireNamespace</span>(<span class="st">"dplyr"</span>, <span class="at">quietly =</span> <span class="cn">TRUE</span>)) <span class="fu">install.packages</span>(<span class="st">"dplyr"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<section id="question-1-create-a-multivariate-time-series-perform-any-interpolations." class="level1">
<h1>Question 1: Create ​​a ​​multivariate​​ time​​ series;​​ perform​​ any ​​interpolations.​​​​</h1>
<section id="load-packages" class="level2">
<h2 class="anchored" data-anchor-id="load-packages">Load Packages</h2>
<div class="cell">
<div class="sourceCode cell-code" id="cb2"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a><span class="co"># </span></span>
<span id="cb2-2"><a href="#cb2-2" aria-hidden="true" tabindex="-1"></a><span class="co"># install.packages("haven")</span></span>
<span id="cb2-3"><a href="#cb2-3" aria-hidden="true" tabindex="-1"></a><span class="co"># install.packages("devtools", dependencies = TRUE)</span></span>
<span id="cb2-4"><a href="#cb2-4" aria-hidden="true" tabindex="-1"></a><span class="co"># install.packages("car")</span></span>
<span id="cb2-5"><a href="#cb2-5" aria-hidden="true" tabindex="-1"></a><span class="co"># install.packages("ggplot2")</span></span>
<span id="cb2-6"><a href="#cb2-6" aria-hidden="true" tabindex="-1"></a><span class="co"># install.packages("plyr")</span></span>
<span id="cb2-7"><a href="#cb2-7" aria-hidden="true" tabindex="-1"></a><span class="co"># install.packages("forecast")</span></span>
<span id="cb2-8"><a href="#cb2-8" aria-hidden="true" tabindex="-1"></a><span class="co"># install.packages("fUnitRoots")</span></span>
<span id="cb2-9"><a href="#cb2-9" aria-hidden="true" tabindex="-1"></a><span class="co"># install.packages("tseries")</span></span>
<span id="cb2-10"><a href="#cb2-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-11"><a href="#cb2-11" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-12"><a href="#cb2-12" aria-hidden="true" tabindex="-1"></a><span class="co">#load packages</span></span>
<span id="cb2-13"><a href="#cb2-13" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(ggplot2)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: package 'ggplot2' was built under R version 4.4.2</code></pre>
</div>
<div class="sourceCode cell-code" id="cb4"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(plyr)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: package 'plyr' was built under R version 4.4.2</code></pre>
</div>
<div class="sourceCode cell-code" id="cb6"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(lmtest)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: package 'lmtest' was built under R version 4.4.2</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Loading required package: zoo</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>
Attaching package: 'zoo'</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>The following objects are masked from 'package:base':

    as.Date, as.Date.numeric</code></pre>
</div>
<div class="sourceCode cell-code" id="cb11"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(car)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: package 'car' was built under R version 4.4.2</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Loading required package: carData</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: package 'carData' was built under R version 4.4.2</code></pre>
</div>
<div class="sourceCode cell-code" id="cb15"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb15-1"><a href="#cb15-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(dplyr)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: package 'dplyr' was built under R version 4.4.2</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>
Attaching package: 'dplyr'</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>The following object is masked from 'package:car':

    recode</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>The following objects are masked from 'package:plyr':

    arrange, count, desc, failwith, id, mutate, rename, summarise,
    summarize</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>The following objects are masked from 'package:stats':

    filter, lag</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>The following objects are masked from 'package:base':

    intersect, setdiff, setequal, union</code></pre>
</div>
<div class="sourceCode cell-code" id="cb22"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb22-1"><a href="#cb22-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(haven)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: package 'haven' was built under R version 4.4.2</code></pre>
</div>
<div class="sourceCode cell-code" id="cb24"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb24-1"><a href="#cb24-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(forecast)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: package 'forecast' was built under R version 4.4.2</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Registered S3 method overwritten by 'quantmod':
  method            from
  as.zoo.data.frame zoo </code></pre>
</div>
<div class="sourceCode cell-code" id="cb27"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb27-1"><a href="#cb27-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(fUnitRoots)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: package 'fUnitRoots' was built under R version 4.4.2</code></pre>
</div>
<div class="sourceCode cell-code" id="cb29"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb29-1"><a href="#cb29-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tseries)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: package 'tseries' was built under R version 4.4.2</code></pre>
</div>
</div>
</section>
<section id="load-the-data-set" class="level2">
<h2 class="anchored" data-anchor-id="load-the-data-set">Load the Data set</h2>
<div class="cell">
<div class="sourceCode cell-code" id="cb31"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb31-1"><a href="#cb31-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Load the haven package</span></span>
<span id="cb31-2"><a href="#cb31-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(haven)</span>
<span id="cb31-3"><a href="#cb31-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb31-4"><a href="#cb31-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb31-5"><a href="#cb31-5" aria-hidden="true" tabindex="-1"></a><span class="co"># Load the Stata file</span></span>
<span id="cb31-6"><a href="#cb31-6" aria-hidden="true" tabindex="-1"></a>file_path <span class="ot">&lt;-</span> <span class="st">"C:/Users/nmv2125/Downloads/GSS_stata (2)/GSS_stata/gss7222_r4.dta"</span></span>
<span id="cb31-7"><a href="#cb31-7" aria-hidden="true" tabindex="-1"></a>gss_data <span class="ot">&lt;-</span> <span class="fu">read_dta</span>(file_path)</span>
<span id="cb31-8"><a href="#cb31-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb31-9"><a href="#cb31-9" aria-hidden="true" tabindex="-1"></a><span class="co"># View the first few rows</span></span>
<span id="cb31-10"><a href="#cb31-10" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(gss_data)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 6 × 6,696
  year     id wrkstat hrs1        hrs2        evwork      occ   prestige wrkslf 
  &lt;dbl&gt; &lt;dbl&gt; &lt;dbl+l&gt; &lt;dbl+lbl&gt;   &lt;dbl+lbl&gt;   &lt;dbl+lbl&gt;   &lt;dbl&gt; &lt;dbl+lb&gt; &lt;dbl+l&gt;
1 1972      1 1 [wor… NA(i) [iap] NA(i) [iap] NA(i) [iap] 205   50       2 [som…
2 1972      2 5 [ret… NA(i) [iap] NA(i) [iap]     1 [yes] 441   45       2 [som…
3 1972      3 2 [wor… NA(i) [iap] NA(i) [iap] NA(i) [iap] 270   44       2 [som…
4 1972      4 1 [wor… NA(i) [iap] NA(i) [iap] NA(i) [iap]   1   57       2 [som…
5 1972      5 7 [kee… NA(i) [iap] NA(i) [iap]     1 [yes] 385   40       2 [som…
6 1972      6 1 [wor… NA(i) [iap] NA(i) [iap] NA(i) [iap] 281   49       2 [som…
# ℹ 6,687 more variables: wrkgovt &lt;dbl+lbl&gt;, commute &lt;dbl+lbl&gt;,
#   industry &lt;dbl+lbl&gt;, occ80 &lt;dbl+lbl&gt;, prestg80 &lt;dbl+lbl&gt;, indus80 &lt;dbl+lbl&gt;,
#   indus07 &lt;dbl+lbl&gt;, occonet &lt;dbl+lbl&gt;, found &lt;dbl+lbl&gt;, occ10 &lt;dbl+lbl&gt;,
#   occindv &lt;dbl+lbl&gt;, occstatus &lt;dbl+lbl&gt;, occtag &lt;dbl+lbl&gt;,
#   prestg10 &lt;dbl+lbl&gt;, prestg105plus &lt;dbl+lbl&gt;, indus10 &lt;dbl+lbl&gt;,
#   indstatus &lt;dbl+lbl&gt;, indtag &lt;dbl+lbl&gt;, marital &lt;dbl+lbl&gt;,
#   martype &lt;dbl+lbl&gt;, agewed &lt;dbl+lbl&gt;, divorce &lt;dbl+lbl&gt;, …</code></pre>
</div>
<div class="sourceCode cell-code" id="cb33"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb33-1"><a href="#cb33-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Check structure of the dataset</span></span>
<span id="cb33-2"><a href="#cb33-2" aria-hidden="true" tabindex="-1"></a><span class="co">#str(gss_data)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Here are the variables I’ve chosen: fefam, educ, happy7, sprtprsn, discaffw</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb34"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb34-1"><a href="#cb34-1" aria-hidden="true" tabindex="-1"></a><span class="co"># print(gss_data$fefam)</span></span>
<span id="cb34-2"><a href="#cb34-2" aria-hidden="true" tabindex="-1"></a><span class="co"># print(gss_data$educ)</span></span>
<span id="cb34-3"><a href="#cb34-3" aria-hidden="true" tabindex="-1"></a><span class="co"># print(gss_data$happy7)</span></span>
<span id="cb34-4"><a href="#cb34-4" aria-hidden="true" tabindex="-1"></a><span class="co"># print(gss_data$sprtprsn)</span></span>
<span id="cb34-5"><a href="#cb34-5" aria-hidden="true" tabindex="-1"></a><span class="co"># print(gss_data$discaffw)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="recode-variables-to-prepare-for-dataset" class="level2">
<h2 class="anchored" data-anchor-id="recode-variables-to-prepare-for-dataset">Recode Variables to Prepare for Dataset</h2>
<div class="cell">
<div class="sourceCode cell-code" id="cb35"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb35-1"><a href="#cb35-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Subset only the relevant variables</span></span>
<span id="cb35-2"><a href="#cb35-2" aria-hidden="true" tabindex="-1"></a>vars <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="st">"year"</span>, <span class="st">"fefam"</span>, <span class="st">"educ"</span>, <span class="st">"happy7"</span>, <span class="st">"sprtprsn"</span>, <span class="st">"discaffw"</span>)</span>
<span id="cb35-3"><a href="#cb35-3" aria-hidden="true" tabindex="-1"></a>sub <span class="ot">&lt;-</span> gss_data[, vars]</span>
<span id="cb35-4"><a href="#cb35-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb35-5"><a href="#cb35-5" aria-hidden="true" tabindex="-1"></a><span class="co"># Recode variables: turn categorical responses into meaningful numeric ones</span></span>
<span id="cb35-6"><a href="#cb35-6" aria-hidden="true" tabindex="-1"></a>sub <span class="ot">&lt;-</span> sub <span class="sc">%&gt;%</span></span>
<span id="cb35-7"><a href="#cb35-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(</span>
<span id="cb35-8"><a href="#cb35-8" aria-hidden="true" tabindex="-1"></a>    <span class="at">fefam_bin =</span> <span class="fu">ifelse</span>(fefam <span class="sc">==</span> <span class="dv">1</span>, <span class="dv">1</span>, <span class="dv">0</span>),  <span class="co"># "strongly agree" as 1, others as 0</span></span>
<span id="cb35-9"><a href="#cb35-9" aria-hidden="true" tabindex="-1"></a>    <span class="at">educ_years =</span> <span class="fu">as.numeric</span>(educ),         <span class="co"># education years already numeric</span></span>
<span id="cb35-10"><a href="#cb35-10" aria-hidden="true" tabindex="-1"></a>    <span class="at">happy_score =</span> <span class="fu">case_when</span>(               <span class="co"># reverse code happiness</span></span>
<span id="cb35-11"><a href="#cb35-11" aria-hidden="true" tabindex="-1"></a>      happy7 <span class="sc">==</span> <span class="dv">1</span> <span class="sc">~</span> <span class="dv">7</span>,  <span class="co"># completely happy = 7</span></span>
<span id="cb35-12"><a href="#cb35-12" aria-hidden="true" tabindex="-1"></a>      happy7 <span class="sc">==</span> <span class="dv">2</span> <span class="sc">~</span> <span class="dv">6</span>,  </span>
<span id="cb35-13"><a href="#cb35-13" aria-hidden="true" tabindex="-1"></a>      happy7 <span class="sc">==</span> <span class="dv">3</span> <span class="sc">~</span> <span class="dv">5</span>,  </span>
<span id="cb35-14"><a href="#cb35-14" aria-hidden="true" tabindex="-1"></a>      happy7 <span class="sc">==</span> <span class="dv">4</span> <span class="sc">~</span> <span class="dv">4</span>,  </span>
<span id="cb35-15"><a href="#cb35-15" aria-hidden="true" tabindex="-1"></a>      happy7 <span class="sc">==</span> <span class="dv">5</span> <span class="sc">~</span> <span class="dv">3</span>,  </span>
<span id="cb35-16"><a href="#cb35-16" aria-hidden="true" tabindex="-1"></a>      happy7 <span class="sc">==</span> <span class="dv">6</span> <span class="sc">~</span> <span class="dv">2</span>,  </span>
<span id="cb35-17"><a href="#cb35-17" aria-hidden="true" tabindex="-1"></a>      happy7 <span class="sc">==</span> <span class="dv">7</span> <span class="sc">~</span> <span class="dv">1</span>,  <span class="co"># completely unhappy = 1</span></span>
<span id="cb35-18"><a href="#cb35-18" aria-hidden="true" tabindex="-1"></a>      <span class="cn">TRUE</span> <span class="sc">~</span> <span class="cn">NA_real_</span></span>
<span id="cb35-19"><a href="#cb35-19" aria-hidden="true" tabindex="-1"></a>    ),</span>
<span id="cb35-20"><a href="#cb35-20" aria-hidden="true" tabindex="-1"></a>    <span class="at">spiritual_score =</span> <span class="fu">case_when</span>(</span>
<span id="cb35-21"><a href="#cb35-21" aria-hidden="true" tabindex="-1"></a>      sprtprsn <span class="sc">==</span> <span class="dv">1</span> <span class="sc">~</span> <span class="dv">4</span>,  <span class="co"># very spiritual = 4</span></span>
<span id="cb35-22"><a href="#cb35-22" aria-hidden="true" tabindex="-1"></a>      sprtprsn <span class="sc">==</span> <span class="dv">2</span> <span class="sc">~</span> <span class="dv">3</span>,  </span>
<span id="cb35-23"><a href="#cb35-23" aria-hidden="true" tabindex="-1"></a>      sprtprsn <span class="sc">==</span> <span class="dv">3</span> <span class="sc">~</span> <span class="dv">2</span>,  </span>
<span id="cb35-24"><a href="#cb35-24" aria-hidden="true" tabindex="-1"></a>      sprtprsn <span class="sc">==</span> <span class="dv">4</span> <span class="sc">~</span> <span class="dv">1</span>,  <span class="co"># not spiritual = 1</span></span>
<span id="cb35-25"><a href="#cb35-25" aria-hidden="true" tabindex="-1"></a>      <span class="cn">TRUE</span> <span class="sc">~</span> <span class="cn">NA_real_</span></span>
<span id="cb35-26"><a href="#cb35-26" aria-hidden="true" tabindex="-1"></a>    ),</span>
<span id="cb35-27"><a href="#cb35-27" aria-hidden="true" tabindex="-1"></a>    <span class="at">discaffw_likely =</span> <span class="fu">case_when</span>(</span>
<span id="cb35-28"><a href="#cb35-28" aria-hidden="true" tabindex="-1"></a>      discaffw <span class="sc">==</span> <span class="dv">1</span> <span class="sc">~</span> <span class="dv">4</span>,  <span class="co"># very likely = 4</span></span>
<span id="cb35-29"><a href="#cb35-29" aria-hidden="true" tabindex="-1"></a>      discaffw <span class="sc">==</span> <span class="dv">2</span> <span class="sc">~</span> <span class="dv">3</span>,  </span>
<span id="cb35-30"><a href="#cb35-30" aria-hidden="true" tabindex="-1"></a>      discaffw <span class="sc">==</span> <span class="dv">3</span> <span class="sc">~</span> <span class="dv">2</span>,  </span>
<span id="cb35-31"><a href="#cb35-31" aria-hidden="true" tabindex="-1"></a>      discaffw <span class="sc">==</span> <span class="dv">4</span> <span class="sc">~</span> <span class="dv">1</span>,  <span class="co"># very unlikely = 1</span></span>
<span id="cb35-32"><a href="#cb35-32" aria-hidden="true" tabindex="-1"></a>      <span class="cn">TRUE</span> <span class="sc">~</span> <span class="cn">NA_real_</span></span>
<span id="cb35-33"><a href="#cb35-33" aria-hidden="true" tabindex="-1"></a>    )</span>
<span id="cb35-34"><a href="#cb35-34" aria-hidden="true" tabindex="-1"></a>  )</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="aggregate-data-by-year" class="level2">
<h2 class="anchored" data-anchor-id="aggregate-data-by-year">Aggregate Data by Year</h2>
<div class="cell">
<div class="sourceCode cell-code" id="cb36"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb36-1"><a href="#cb36-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Group data by year and calculate means, ignoring NA values</span></span>
<span id="cb36-2"><a href="#cb36-2" aria-hidden="true" tabindex="-1"></a>by_year <span class="ot">&lt;-</span> sub <span class="sc">%&gt;%</span></span>
<span id="cb36-3"><a href="#cb36-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(year) <span class="sc">%&gt;%</span></span>
<span id="cb36-4"><a href="#cb36-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarise</span>(</span>
<span id="cb36-5"><a href="#cb36-5" aria-hidden="true" tabindex="-1"></a>    <span class="at">fefam_pct =</span> <span class="fu">mean</span>(fefam_bin, <span class="at">na.rm =</span> <span class="cn">TRUE</span>) <span class="sc">*</span> <span class="dv">100</span>,  <span class="co"># Percentage who "strongly agree"</span></span>
<span id="cb36-6"><a href="#cb36-6" aria-hidden="true" tabindex="-1"></a>    <span class="at">avg_educ =</span> <span class="fu">mean</span>(educ_years, <span class="at">na.rm =</span> <span class="cn">TRUE</span>),        <span class="co"># Average education years</span></span>
<span id="cb36-7"><a href="#cb36-7" aria-hidden="true" tabindex="-1"></a>    <span class="at">avg_happy =</span> <span class="fu">mean</span>(happy_score, <span class="at">na.rm =</span> <span class="cn">TRUE</span>),      <span class="co"># Average happiness score</span></span>
<span id="cb36-8"><a href="#cb36-8" aria-hidden="true" tabindex="-1"></a>    <span class="at">avg_spiritual =</span> <span class="fu">mean</span>(spiritual_score, <span class="at">na.rm =</span> <span class="cn">TRUE</span>),  <span class="co"># Avg spirituality</span></span>
<span id="cb36-9"><a href="#cb36-9" aria-hidden="true" tabindex="-1"></a>    <span class="at">avg_discaffw =</span> <span class="fu">mean</span>(discaffw_likely, <span class="at">na.rm =</span> <span class="cn">TRUE</span>)    <span class="co"># Avg likelihood of discrimination</span></span>
<span id="cb36-10"><a href="#cb36-10" aria-hidden="true" tabindex="-1"></a>  )</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="interpolate-missing-years" class="level2">
<h2 class="anchored" data-anchor-id="interpolate-missing-years">Interpolate Missing Years</h2>
<div class="cell">
<div class="sourceCode cell-code" id="cb37"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb37-1"><a href="#cb37-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Add missing years explicitly if required</span></span>
<span id="cb37-2"><a href="#cb37-2" aria-hidden="true" tabindex="-1"></a>all_years <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(<span class="at">year =</span> <span class="fu">seq</span>(<span class="fu">min</span>(by_year<span class="sc">$</span>year), <span class="fu">max</span>(by_year<span class="sc">$</span>year), <span class="at">by =</span> <span class="dv">1</span>))</span>
<span id="cb37-3"><a href="#cb37-3" aria-hidden="true" tabindex="-1"></a>by_year <span class="ot">&lt;-</span> <span class="fu">full_join</span>(by_year, all_years, <span class="at">by =</span> <span class="st">"year"</span>) <span class="sc">%&gt;%</span></span>
<span id="cb37-4"><a href="#cb37-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">arrange</span>(year)</span>
<span id="cb37-5"><a href="#cb37-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb37-6"><a href="#cb37-6" aria-hidden="true" tabindex="-1"></a><span class="co"># Interpolate missing values for smoother time series</span></span>
<span id="cb37-7"><a href="#cb37-7" aria-hidden="true" tabindex="-1"></a>by_year_interp <span class="ot">&lt;-</span> by_year <span class="sc">%&gt;%</span></span>
<span id="cb37-8"><a href="#cb37-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(</span>
<span id="cb37-9"><a href="#cb37-9" aria-hidden="true" tabindex="-1"></a>    <span class="at">fefam_pct =</span> <span class="fu">na.approx</span>(fefam_pct, <span class="at">na.rm =</span> <span class="cn">FALSE</span>),</span>
<span id="cb37-10"><a href="#cb37-10" aria-hidden="true" tabindex="-1"></a>    <span class="at">avg_educ =</span> <span class="fu">na.approx</span>(avg_educ, <span class="at">na.rm =</span> <span class="cn">FALSE</span>),</span>
<span id="cb37-11"><a href="#cb37-11" aria-hidden="true" tabindex="-1"></a>    <span class="at">avg_happy =</span> <span class="fu">na.approx</span>(avg_happy, <span class="at">na.rm =</span> <span class="cn">FALSE</span>),</span>
<span id="cb37-12"><a href="#cb37-12" aria-hidden="true" tabindex="-1"></a>    <span class="at">avg_spiritual =</span> <span class="fu">na.approx</span>(avg_spiritual, <span class="at">na.rm =</span> <span class="cn">FALSE</span>),</span>
<span id="cb37-13"><a href="#cb37-13" aria-hidden="true" tabindex="-1"></a>    <span class="at">avg_discaffw =</span> <span class="fu">na.approx</span>(avg_discaffw, <span class="at">na.rm =</span> <span class="cn">FALSE</span>)</span>
<span id="cb37-14"><a href="#cb37-14" aria-hidden="true" tabindex="-1"></a>  )</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="visualize-clean-data" class="level2">
<h2 class="anchored" data-anchor-id="visualize-clean-data">Visualize Clean Data</h2>
<div class="cell">
<div class="sourceCode cell-code" id="cb38"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb38-1"><a href="#cb38-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Convert to long format for easier plotting</span></span>
<span id="cb38-2"><a href="#cb38-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidyr)</span>
<span id="cb38-3"><a href="#cb38-3" aria-hidden="true" tabindex="-1"></a>by_year_long <span class="ot">&lt;-</span> <span class="fu">pivot_longer</span>(by_year_interp, <span class="at">cols =</span> <span class="sc">-</span>year, <span class="at">names_to =</span> <span class="st">"variable"</span>, <span class="at">values_to =</span> <span class="st">"value"</span>)</span>
<span id="cb38-4"><a href="#cb38-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb38-5"><a href="#cb38-5" aria-hidden="true" tabindex="-1"></a><span class="co"># Plot the time series for all variables</span></span>
<span id="cb38-6"><a href="#cb38-6" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(by_year_long, <span class="fu">aes</span>(<span class="at">x =</span> year, <span class="at">y =</span> value, <span class="at">color =</span> variable)) <span class="sc">+</span></span>
<span id="cb38-7"><a href="#cb38-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_line</span>(<span class="at">linewidth =</span> <span class="dv">1</span>) <span class="sc">+</span>  <span class="co"># Updated size aesthetic</span></span>
<span id="cb38-8"><a href="#cb38-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>() <span class="sc">+</span></span>
<span id="cb38-9"><a href="#cb38-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">"Multivariate Time Series (Cleaned and Interpolated)"</span>,</span>
<span id="cb38-10"><a href="#cb38-10" aria-hidden="true" tabindex="-1"></a>       <span class="at">x =</span> <span class="st">"Year"</span>, <span class="at">y =</span> <span class="st">"Value"</span>, <span class="at">color =</span> <span class="st">"Variable"</span>) <span class="sc">+</span></span>
<span id="cb38-11"><a href="#cb38-11" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: Removed 85 rows containing missing values or values outside the scale range
(`geom_line()`).</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: Removed 85 rows containing missing values or values outside the scale range
(`geom_point()`).</code></pre>
</div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="ARIMA_files/figure-html/unnamed-chunk-8-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
</section>
</section>
<section id="question-2-graph-the-relationships-between-x-and-y.-explain-how-you-think-y-should-relate-to-your-key-xs." class="level1">
<h1>Question 2: ​Graph ​​the​​ relationships ​​between ​​X​​ and​​ Y.​​​​ Explain ​​how​​ you ​​think​​ Y​​ should ​​relate​​ to​​ your ​​key​​ Xs.​​​​</h1>
<section id="melt-the-time-series" class="level2">
<h2 class="anchored" data-anchor-id="melt-the-time-series">Melt the Time Series:</h2>
<p>reshape the cleaned time series data into a long format. This makes it easy to plot different variables together.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb41"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb41-1"><a href="#cb41-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(reshape2)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: package 'reshape2' was built under R version 4.4.2</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>
Attaching package: 'reshape2'</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>The following object is masked from 'package:tidyr':

    smiths</code></pre>
</div>
<div class="sourceCode cell-code" id="cb45"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb45-1"><a href="#cb45-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Melt the data into long format for plotting</span></span>
<span id="cb45-2"><a href="#cb45-2" aria-hidden="true" tabindex="-1"></a>melt_my_ts <span class="ot">&lt;-</span> <span class="cf">function</span>(ts_data, time_var, keep_vars) {</span>
<span id="cb45-3"><a href="#cb45-3" aria-hidden="true" tabindex="-1"></a>  <span class="co"># ts_data: data.frame of my time series</span></span>
<span id="cb45-4"><a href="#cb45-4" aria-hidden="true" tabindex="-1"></a>  <span class="co"># time_var: name of the time column</span></span>
<span id="cb45-5"><a href="#cb45-5" aria-hidden="true" tabindex="-1"></a>  <span class="co"># keep_vars: variables to keep for plotting</span></span>
<span id="cb45-6"><a href="#cb45-6" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb45-7"><a href="#cb45-7" aria-hidden="true" tabindex="-1"></a>  <span class="co"># Ensure time variable is in keep.vars</span></span>
<span id="cb45-8"><a href="#cb45-8" aria-hidden="true" tabindex="-1"></a>  <span class="cf">if</span> (<span class="sc">!</span>(time_var <span class="sc">%in%</span> keep_vars)) {</span>
<span id="cb45-9"><a href="#cb45-9" aria-hidden="true" tabindex="-1"></a>    keep_vars <span class="ot">&lt;-</span> <span class="fu">c</span>(keep_vars, time_var)</span>
<span id="cb45-10"><a href="#cb45-10" aria-hidden="true" tabindex="-1"></a>  }</span>
<span id="cb45-11"><a href="#cb45-11" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb45-12"><a href="#cb45-12" aria-hidden="true" tabindex="-1"></a>  melted_data <span class="ot">&lt;-</span> ts_data[, keep_vars]</span>
<span id="cb45-13"><a href="#cb45-13" aria-hidden="true" tabindex="-1"></a>  melted_data <span class="ot">&lt;-</span> <span class="fu">melt</span>(melted_data, <span class="at">id.vars =</span> time_var)</span>
<span id="cb45-14"><a href="#cb45-14" aria-hidden="true" tabindex="-1"></a>  <span class="fu">colnames</span>(melted_data)[<span class="fu">which</span>(<span class="fu">colnames</span>(melted_data) <span class="sc">==</span> time_var)] <span class="ot">&lt;-</span> <span class="st">"time"</span></span>
<span id="cb45-15"><a href="#cb45-15" aria-hidden="true" tabindex="-1"></a>  <span class="fu">return</span>(melted_data)</span>
<span id="cb45-16"><a href="#cb45-16" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb45-17"><a href="#cb45-17" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb45-18"><a href="#cb45-18" aria-hidden="true" tabindex="-1"></a><span class="co"># Variables to plot</span></span>
<span id="cb45-19"><a href="#cb45-19" aria-hidden="true" tabindex="-1"></a>keep_vars <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="st">"year"</span>, <span class="st">"fefam_pct"</span>, <span class="st">"avg_educ"</span>, <span class="st">"avg_happy"</span>, <span class="st">"avg_spiritual"</span>, <span class="st">"avg_discaffw"</span>)</span>
<span id="cb45-20"><a href="#cb45-20" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb45-21"><a href="#cb45-21" aria-hidden="true" tabindex="-1"></a><span class="co"># Melt the data</span></span>
<span id="cb45-22"><a href="#cb45-22" aria-hidden="true" tabindex="-1"></a>plot_data <span class="ot">&lt;-</span> <span class="fu">melt_my_ts</span>(by_year_interp, <span class="at">time_var =</span> <span class="st">"year"</span>, <span class="at">keep_vars =</span> keep_vars)</span>
<span id="cb45-23"><a href="#cb45-23" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(plot_data)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>  time  variable    value
1 1972 fefam_pct       NA
2 1973 fefam_pct       NA
3 1974 fefam_pct       NA
4 1975 fefam_pct       NA
5 1976 fefam_pct       NA
6 1977 fefam_pct 18.29674</code></pre>
</div>
</div>
</section>
<section id="define-a-plotting-function" class="level2">
<h2 class="anchored" data-anchor-id="define-a-plotting-function">Define a Plotting Function</h2>
<div class="cell">
<div class="sourceCode cell-code" id="cb47"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb47-1"><a href="#cb47-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(ggplot2)</span>
<span id="cb47-2"><a href="#cb47-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb47-3"><a href="#cb47-3" aria-hidden="true" tabindex="-1"></a>plot_my_ts <span class="ot">&lt;-</span> <span class="cf">function</span>(data, varlist, <span class="at">line =</span> <span class="cn">TRUE</span>, <span class="at">point =</span> <span class="cn">TRUE</span>, <span class="at">pointsize =</span> <span class="dv">3</span>, <span class="at">linewidth =</span> <span class="fl">1.25</span>) {</span>
<span id="cb47-4"><a href="#cb47-4" aria-hidden="true" tabindex="-1"></a>  <span class="co"># data: melted data frame</span></span>
<span id="cb47-5"><a href="#cb47-5" aria-hidden="true" tabindex="-1"></a>  <span class="co"># varlist: character vector of variables to plot</span></span>
<span id="cb47-6"><a href="#cb47-6" aria-hidden="true" tabindex="-1"></a>  <span class="cf">if</span> (<span class="fu">missing</span>(varlist)) {</span>
<span id="cb47-7"><a href="#cb47-7" aria-hidden="true" tabindex="-1"></a>    gg <span class="ot">&lt;-</span> <span class="fu">ggplot</span>(data, <span class="fu">aes</span>(<span class="at">x =</span> time, <span class="at">y =</span> value, <span class="at">color =</span> variable))</span>
<span id="cb47-8"><a href="#cb47-8" aria-hidden="true" tabindex="-1"></a>  } <span class="cf">else</span> {</span>
<span id="cb47-9"><a href="#cb47-9" aria-hidden="true" tabindex="-1"></a>    gg <span class="ot">&lt;-</span> <span class="fu">ggplot</span>(data[data<span class="sc">$</span>variable <span class="sc">%in%</span> varlist, ], <span class="fu">aes</span>(<span class="at">x =</span> time, <span class="at">y =</span> value, <span class="at">color =</span> variable))</span>
<span id="cb47-10"><a href="#cb47-10" aria-hidden="true" tabindex="-1"></a>  }</span>
<span id="cb47-11"><a href="#cb47-11" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb47-12"><a href="#cb47-12" aria-hidden="true" tabindex="-1"></a>  <span class="cf">if</span> (line) gg <span class="ot">&lt;-</span> gg <span class="sc">+</span> <span class="fu">geom_line</span>(<span class="at">linewidth =</span> linewidth)</span>
<span id="cb47-13"><a href="#cb47-13" aria-hidden="true" tabindex="-1"></a>  <span class="cf">if</span> (point) gg <span class="ot">&lt;-</span> gg <span class="sc">+</span> <span class="fu">geom_point</span>(<span class="at">size =</span> pointsize)</span>
<span id="cb47-14"><a href="#cb47-14" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb47-15"><a href="#cb47-15" aria-hidden="true" tabindex="-1"></a>  gg <span class="ot">&lt;-</span> gg <span class="sc">+</span> <span class="fu">labs</span>(<span class="at">x =</span> <span class="st">"Year"</span>, <span class="at">y =</span> <span class="st">"Value"</span>, <span class="at">color =</span> <span class="st">"Variable"</span>) <span class="sc">+</span></span>
<span id="cb47-16"><a href="#cb47-16" aria-hidden="true" tabindex="-1"></a>    <span class="fu">theme_minimal</span>() <span class="sc">+</span></span>
<span id="cb47-17"><a href="#cb47-17" aria-hidden="true" tabindex="-1"></a>    <span class="fu">theme</span>(<span class="at">legend.position =</span> <span class="st">"bottom"</span>) <span class="sc">+</span></span>
<span id="cb47-18"><a href="#cb47-18" aria-hidden="true" tabindex="-1"></a>    <span class="fu">scale_x_continuous</span>(<span class="at">breaks =</span> <span class="fu">seq</span>(<span class="fu">min</span>(data<span class="sc">$</span>time), <span class="fu">max</span>(data<span class="sc">$</span>time), <span class="at">by =</span> <span class="dv">5</span>))</span>
<span id="cb47-19"><a href="#cb47-19" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb47-20"><a href="#cb47-20" aria-hidden="true" tabindex="-1"></a>  <span class="fu">return</span>(gg)</span>
<span id="cb47-21"><a href="#cb47-21" aria-hidden="true" tabindex="-1"></a>}</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="generate-plot-for-relationships-between-x-y" class="level2">
<h2 class="anchored" data-anchor-id="generate-plot-for-relationships-between-x-y">Generate Plot for Relationships Between X &amp; Y</h2>
<div class="cell">
<div class="sourceCode cell-code" id="cb48"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb48-1"><a href="#cb48-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Plot fefam_pct over time (Y variable)</span></span>
<span id="cb48-2"><a href="#cb48-2" aria-hidden="true" tabindex="-1"></a>plot_fefam <span class="ot">&lt;-</span> <span class="fu">plot_my_ts</span>(plot_data, <span class="at">varlist =</span> <span class="fu">c</span>(<span class="st">"fefam_pct"</span>))</span>
<span id="cb48-3"><a href="#cb48-3" aria-hidden="true" tabindex="-1"></a>plot_fefam</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: Removed 5 rows containing missing values or values outside the scale range
(`geom_line()`).</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: Removed 5 rows containing missing values or values outside the scale range
(`geom_point()`).</code></pre>
</div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="ARIMA_files/figure-html/unnamed-chunk-11-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="sourceCode cell-code" id="cb51"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb51-1"><a href="#cb51-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Plot avg_educ (X) and fefam_pct (Y)</span></span>
<span id="cb51-2"><a href="#cb51-2" aria-hidden="true" tabindex="-1"></a>plot_educ <span class="ot">&lt;-</span> <span class="fu">plot_my_ts</span>(plot_data, <span class="at">varlist =</span> <span class="fu">c</span>(<span class="st">"fefam_pct"</span>, <span class="st">"avg_educ"</span>))</span>
<span id="cb51-3"><a href="#cb51-3" aria-hidden="true" tabindex="-1"></a>plot_educ</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: Removed 5 rows containing missing values or values outside the scale range
(`geom_line()`).
Removed 5 rows containing missing values or values outside the scale range
(`geom_point()`).</code></pre>
</div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="ARIMA_files/figure-html/unnamed-chunk-11-2.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="sourceCode cell-code" id="cb53"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb53-1"><a href="#cb53-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Plot avg_happy (X) and fefam_pct (Y)</span></span>
<span id="cb53-2"><a href="#cb53-2" aria-hidden="true" tabindex="-1"></a>plot_happy <span class="ot">&lt;-</span> <span class="fu">plot_my_ts</span>(plot_data, <span class="at">varlist =</span> <span class="fu">c</span>(<span class="st">"fefam_pct"</span>, <span class="st">"avg_happy"</span>))</span>
<span id="cb53-3"><a href="#cb53-3" aria-hidden="true" tabindex="-1"></a>plot_happy</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: Removed 35 rows containing missing values or values outside the scale range
(`geom_line()`).</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: Removed 35 rows containing missing values or values outside the scale range
(`geom_point()`).</code></pre>
</div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="ARIMA_files/figure-html/unnamed-chunk-11-3.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="sourceCode cell-code" id="cb56"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb56-1"><a href="#cb56-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Plot avg_spiritual (X) and fefam_pct (Y)</span></span>
<span id="cb56-2"><a href="#cb56-2" aria-hidden="true" tabindex="-1"></a>plot_spiritual <span class="ot">&lt;-</span> <span class="fu">plot_my_ts</span>(plot_data, <span class="at">varlist =</span> <span class="fu">c</span>(<span class="st">"fefam_pct"</span>, <span class="st">"avg_spiritual"</span>))</span>
<span id="cb56-3"><a href="#cb56-3" aria-hidden="true" tabindex="-1"></a>plot_spiritual</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: Removed 31 rows containing missing values or values outside the scale range
(`geom_line()`).</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: Removed 31 rows containing missing values or values outside the scale range
(`geom_point()`).</code></pre>
</div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="ARIMA_files/figure-html/unnamed-chunk-11-4.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="sourceCode cell-code" id="cb59"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb59-1"><a href="#cb59-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Plot avg_discaffw (X) and fefam_pct (Y)</span></span>
<span id="cb59-2"><a href="#cb59-2" aria-hidden="true" tabindex="-1"></a>plot_discaffw <span class="ot">&lt;-</span> <span class="fu">plot_my_ts</span>(plot_data, <span class="at">varlist =</span> <span class="fu">c</span>(<span class="st">"fefam_pct"</span>, <span class="st">"avg_discaffw"</span>))</span>
<span id="cb59-3"><a href="#cb59-3" aria-hidden="true" tabindex="-1"></a>plot_discaffw</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: Removed 29 rows containing missing values or values outside the scale range
(`geom_line()`).</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: Removed 29 rows containing missing values or values outside the scale range
(`geom_point()`).</code></pre>
</div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="ARIMA_files/figure-html/unnamed-chunk-11-5.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<ul>
<li><p><strong><code>fefam_pct</code> vs <code>avg_educ</code></strong>: kind of <strong>negative relationship</strong>—higher education could correlate with less agreement to traditional gender roles.</p></li>
<li><p><strong><code>fefam_pct</code> vs <code>avg_happy</code></strong>: Happiness have a neutral relationship, depending on individual perspectives.</p></li>
<li><p><strong><code>fefam_pct</code> vs <code>avg_spiritual</code></strong>: I thought higher spirituality might correlate with higher agreement to traditional family roles, or lower agreement to traditional family roles, depending on the religious and spirituality values. Turns out, spirituality is quiet neutral</p></li>
<li><p><strong><code>fefam_pct</code> vs <code>avg_discaffw</code></strong>: I thought if people perceive greater workplace discrimination against women (<code>discaffw</code>), agreement to traditional roles might also increase, however, it seems neutral and there doesn’t seem to be a relationship</p></li>
</ul>
</section>
</section>
<section id="question-3-run-a-simple-time-series-regression-with-one-x-and-no-trend.-interpret-it." class="level1">
<h1>Question 3: ​​Run​​ a​​ simple​​ time​​ series​​ regression,​​ with ​​one​​ X​​ and​​ no ​​trend.​​​​ Interpret​​ it.​​​​</h1>
<section id="simple-time-series-regression" class="level2">
<h2 class="anchored" data-anchor-id="simple-time-series-regression">Simple Time Series Regression</h2>
<div class="cell">
<div class="sourceCode cell-code" id="cb62"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb62-1"><a href="#cb62-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Simple time series regression: fefam_pct ~ avg_educ</span></span>
<span id="cb62-2"><a href="#cb62-2" aria-hidden="true" tabindex="-1"></a>lm_fefam <span class="ot">&lt;-</span> <span class="fu">lm</span>(fefam_pct <span class="sc">~</span> avg_educ, <span class="at">data =</span> by_year_interp)</span>
<span id="cb62-3"><a href="#cb62-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb62-4"><a href="#cb62-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Summary of the regression</span></span>
<span id="cb62-5"><a href="#cb62-5" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(lm_fefam)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = fefam_pct ~ avg_educ, data = by_year_interp)

Residuals:
    Min      1Q  Median      3Q     Max 
-3.1595 -0.9548 -0.4269  1.0700  3.9326 

Coefficients:
            Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)  58.3565     5.0702  11.510 7.35e-15 ***
avg_educ     -3.7638     0.3855  -9.763 1.39e-12 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 1.83 on 44 degrees of freedom
  (5 observations deleted due to missingness)
Multiple R-squared:  0.6842,    Adjusted R-squared:  0.677 
F-statistic: 95.31 on 1 and 44 DF,  p-value: 1.394e-12</code></pre>
</div>
</div>
<p><strong>Slope (avg_educ)</strong>: -3.7638</p>
<ul>
<li><p>For every <strong>one-unit increase</strong> in average education (<code>avg_educ</code>), the percentage agreeing with traditional family roles (<code>fefam_pct</code>) <strong>decreases by 3.76 percentage points</strong>.</p></li>
<li><p>The negative coefficient suggests that <strong>higher education levels are associated with a decline in agreement</strong> with traditional family norms.</p></li>
</ul>
<p><strong>P-values</strong>:</p>
<ul>
<li><p>Both the <strong>Intercept</strong> and <code>avg_educ</code> are highly significant (<code>p &lt; 0.001</code>), as seen by the <code>***</code> symbols.</p></li>
<li><p>This means there is very strong evidence that average education (<code>avg_educ</code>) influences <code>fefam_pct</code>.</p></li>
</ul>
</section>
<section id="test-for-heteroskedascity" class="level2">
<h2 class="anchored" data-anchor-id="test-for-heteroskedascity">Test for Heteroskedascity</h2>
<div class="cell">
<div class="sourceCode cell-code" id="cb64"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb64-1"><a href="#cb64-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Install and load lmtest for Breusch-Pagan Test</span></span>
<span id="cb64-2"><a href="#cb64-2" aria-hidden="true" tabindex="-1"></a><span class="fu">install.packages</span>(<span class="st">"lmtest"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: package 'lmtest' is in use and will not be installed</code></pre>
</div>
<div class="sourceCode cell-code" id="cb66"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb66-1"><a href="#cb66-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(lmtest)</span>
<span id="cb66-2"><a href="#cb66-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb66-3"><a href="#cb66-3" aria-hidden="true" tabindex="-1"></a><span class="co"># Test for heteroskedasticity</span></span>
<span id="cb66-4"><a href="#cb66-4" aria-hidden="true" tabindex="-1"></a><span class="fu">bptest</span>(lm_fefam)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    studentized Breusch-Pagan test

data:  lm_fefam
BP = 10.235, df = 1, p-value = 0.001378</code></pre>
</div>
</div>
<p>The Breusch-Pagan test checks whether the variance of the residuals (errors) is constant or changes systematically with the predictor variable. Non-constant variance is called heteroskedasticity, which can affect the validity of regression results.</p>
<pre><code>studentized Breusch-Pagan test  data:  lm_fefam BP = 10.235, df = 1, p-value = 0.001378 </code></pre>
<ul>
<li><p><strong>BP statistic = 10.235</strong></p>
<ul>
<li>This is the test statistic for the Breusch-Pagan test. A larger value indicates more evidence of heteroskedasticity.</li>
</ul></li>
<li><p><strong>Degrees of freedom (df) = 1</strong></p>
<ul>
<li>This corresponds to the single predictor variable <code>avg_educ</code> in my model.</li>
</ul></li>
<li><p><strong>p-value = 0.001378</strong></p>
<ul>
<li>Since the p-value is <strong>less than 0.05</strong>, we <strong>reject the null hypothesis</strong> of homoskedasticity (constant variance).</li>
</ul></li>
</ul>
<p>The residuals’ variance is not constant and is likely related to avg_educ.</p>
</section>
<section id="checking-for-autocorrelation-in-residuals" class="level2">
<h2 class="anchored" data-anchor-id="checking-for-autocorrelation-in-residuals">Checking for Autocorrelation in Residuals</h2>
<div class="cell">
<div class="sourceCode cell-code" id="cb69"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb69-1"><a href="#cb69-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Extract residuals</span></span>
<span id="cb69-2"><a href="#cb69-2" aria-hidden="true" tabindex="-1"></a>resid_fefam <span class="ot">&lt;-</span> lm_fefam<span class="sc">$</span>residuals</span>
<span id="cb69-3"><a href="#cb69-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb69-4"><a href="#cb69-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Autocorrelation Function (ACF) plot</span></span>
<span id="cb69-5"><a href="#cb69-5" aria-hidden="true" tabindex="-1"></a><span class="fu">acf</span>(resid_fefam, <span class="at">main =</span> <span class="st">"ACF of Residuals"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="ARIMA_files/figure-html/unnamed-chunk-14-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="sourceCode cell-code" id="cb70"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb70-1"><a href="#cb70-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Partial Autocorrelation Function (PACF) plot</span></span>
<span id="cb70-2"><a href="#cb70-2" aria-hidden="true" tabindex="-1"></a><span class="fu">pacf</span>(resid_fefam, <span class="at">main =</span> <span class="st">"PACF of Residuals"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="ARIMA_files/figure-html/unnamed-chunk-14-2.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="sourceCode cell-code" id="cb71"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb71-1"><a href="#cb71-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Durbin-Watson Test</span></span>
<span id="cb71-2"><a href="#cb71-2" aria-hidden="true" tabindex="-1"></a><span class="co">#dwtest(lm_fefam)</span></span>
<span id="cb71-3"><a href="#cb71-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb71-4"><a href="#cb71-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Breusch-Godfrey Test for higher-order autocorrelation</span></span>
<span id="cb71-5"><a href="#cb71-5" aria-hidden="true" tabindex="-1"></a><span class="co">#bgtest(lm_fefam)</span></span>
<span id="cb71-6"><a href="#cb71-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb71-7"><a href="#cb71-7" aria-hidden="true" tabindex="-1"></a><span class="co"># Durbin-Watson test with multiple lags</span></span>
<span id="cb71-8"><a href="#cb71-8" aria-hidden="true" tabindex="-1"></a><span class="co">#durbinWatsonTest(lm_fefam, max.lag = 3)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="plot-residuals-over-time" class="level2">
<h2 class="anchored" data-anchor-id="plot-residuals-over-time">Plot Residuals Over Time</h2>
<div class="cell">
<div class="sourceCode cell-code" id="cb72"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb72-1"><a href="#cb72-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(resid_fefam, <span class="at">type =</span> <span class="st">"o"</span>, <span class="at">main =</span> <span class="st">"Residuals Over Time"</span>, <span class="at">xlab =</span> <span class="st">"Index"</span>, <span class="at">ylab =</span> <span class="st">"Residuals"</span>)</span>
<span id="cb72-2"><a href="#cb72-2" aria-hidden="true" tabindex="-1"></a><span class="fu">abline</span>(<span class="at">h =</span> <span class="dv">0</span>, <span class="at">col =</span> <span class="st">"blue"</span>, <span class="at">lwd =</span> <span class="dv">2</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="ARIMA_files/figure-html/unnamed-chunk-15-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
</section>
</section>
<section id="question-5-consider-running-a-time-series-regression-with-many-xs-and-trend.-interpret-that.-check-vif." class="level1">
<h1>Question 5: ​​Consider​​ running​​ a​​ time ​​series ​​regression ​​with​​ many ​​Xs​​ and​​ trend.​​​​ Interpret​​ that.​​​​ Check​​ VIF.​​​​</h1>
<section id="multiple-regression-with-trend" class="level2">
<h2 class="anchored" data-anchor-id="multiple-regression-with-trend">Multiple Regression with Trend</h2>
<p>Running a multiple regression with <code>avg_educ</code>, <code>avg_happy</code>, <code>avg_spiritual</code>, and a <strong>trend</strong> variable (<code>year</code>).</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb73"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb73-1"><a href="#cb73-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Add more predictors (e.g., avg_happy, avg_spiritual) and a trend (year)</span></span>
<span id="cb73-2"><a href="#cb73-2" aria-hidden="true" tabindex="-1"></a>lm_fefam_multi <span class="ot">&lt;-</span> <span class="fu">lm</span>(fefam_pct <span class="sc">~</span> avg_educ <span class="sc">+</span> avg_happy <span class="sc">+</span> avg_spiritual <span class="sc">+</span> year, <span class="at">data =</span> by_year_interp)</span>
<span id="cb73-3"><a href="#cb73-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb73-4"><a href="#cb73-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Summary of the model</span></span>
<span id="cb73-5"><a href="#cb73-5" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(lm_fefam_multi)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = fefam_pct ~ avg_educ + avg_happy + avg_spiritual + 
    year, data = by_year_interp)

Residuals:
    Min      1Q  Median      3Q     Max 
-0.4827 -0.1563 -0.1013  0.0387  0.9815 

Coefficients:
               Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)   692.97907  103.35688   6.705 5.06e-06 ***
avg_educ       -2.49096    0.64289  -3.875  0.00134 ** 
avg_happy      -8.97892    5.38964  -1.666  0.11518    
avg_spiritual -11.76898    3.64716  -3.227  0.00527 ** 
year           -0.28287    0.04021  -7.035 2.82e-06 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 0.3418 on 16 degrees of freedom
  (30 observations deleted due to missingness)
Multiple R-squared:  0.9645,    Adjusted R-squared:  0.9557 
F-statistic: 108.8 on 4 and 16 DF,  p-value: 2.182e-11</code></pre>
</div>
</div>
<ul>
<li><p><strong><code>avg_educ</code> (-2.49, p = 0.00134)</strong>:</p>
<ul>
<li><p>For each additional unit increase in <strong>average education</strong>, <code>fefam_pct</code> decreases by <strong>2.49 percentage points</strong>.</p></li>
<li><p>This is statistically significant at the <strong>1% level</strong>, indicating a strong negative relationship.</p></li>
</ul></li>
<li><p><strong><code>avg_happy</code> (-8.98, p = 0.11518)</strong>:</p>
<ul>
<li><p>A unit increase in <strong>average happiness</strong> is associated with a decrease of <strong>8.98 percentage points</strong> in <code>fefam_pct</code>.</p></li>
<li><p>However, this effect is <strong>not statistically significant</strong> (p &gt; 0.05).</p></li>
</ul></li>
<li><p><strong><code>avg_spiritual</code> (-11.77, p = 0.00527)</strong>:</p>
<ul>
<li><p>A unit increase in <strong>average spirituality</strong> reduces <code>fefam_pct</code> by <strong>11.77 percentage points</strong>.</p></li>
<li><p>This is significant at the <strong>1% level</strong>, suggesting a strong negative relationship.</p></li>
</ul></li>
<li><p><strong><code>year</code> (-0.28287, p = 2.82e-06)</strong>:</p>
<ul>
<li><p>Over time, <code>fefam_pct</code> decreases by about <strong>0.28 percentage points per year</strong>.</p></li>
<li><p>This is highly significant, showing a strong downward trend over time.</p></li>
</ul></li>
</ul>
<section id="model-fit" class="level4">
<h4 class="anchored" data-anchor-id="model-fit"><strong>Model Fit:</strong></h4>
<ul>
<li><p><strong>R-squared = 0.9645</strong>:</p>
<ul>
<li>About <strong>96.45% of the variation</strong> in <code>fefam_pct</code> is explained by the predictors.</li>
</ul></li>
<li><p><strong>Adjusted R-squared = 0.9557</strong>:</p>
<ul>
<li>Adjusted for the number of predictors, this still indicates an excellent fit.</li>
</ul></li>
<li><p><strong>F-statistic = 108.8, p &lt; 0.001</strong>:</p>
<ul>
<li>The model as a whole is highly significant.</li>
</ul></li>
</ul>
</section>
</section>
<section id="check-for-multicollinearity-variance-inflation-factor-vif" class="level2">
<h2 class="anchored" data-anchor-id="check-for-multicollinearity-variance-inflation-factor-vif">Check for Multicollinearity: Variance Inflation Factor (VIF)</h2>
<p>Check for multicollinearity using VIF</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb75"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb75-1"><a href="#cb75-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Install and load the 'car' package for VIF</span></span>
<span id="cb75-2"><a href="#cb75-2" aria-hidden="true" tabindex="-1"></a><span class="fu">install.packages</span>(<span class="st">"car"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: package 'car' is in use and will not be installed</code></pre>
</div>
<div class="sourceCode cell-code" id="cb77"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb77-1"><a href="#cb77-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(car)</span>
<span id="cb77-2"><a href="#cb77-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb77-3"><a href="#cb77-3" aria-hidden="true" tabindex="-1"></a><span class="co"># Check VIF values</span></span>
<span id="cb77-4"><a href="#cb77-4" aria-hidden="true" tabindex="-1"></a><span class="fu">vif</span>(lm_fefam_multi)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>     avg_educ     avg_happy avg_spiritual          year 
     9.599775     16.675974      7.285929     10.654194 </code></pre>
</div>
</div>
<section id="interpretation" class="level4">
<h4 class="anchored" data-anchor-id="interpretation"><strong>Interpretation:</strong></h4>
<ul>
<li><p><strong>VIF &gt; 5</strong> for all predictors: This means <strong>moderate to severe multicollinearity</strong>.</p></li>
<li><p><strong><code>avg_happy</code> (16.68)</strong> and <strong><code>year</code> (10.65)</strong> have particularly high VIF values, which suggests that these variables are highly correlated with each other or with other predictors.</p></li>
</ul>
</section>
<section id="implications-of-high-vif" class="level4">
<h4 class="anchored" data-anchor-id="implications-of-high-vif"><strong>Implications of High VIF:</strong></h4>
<ul>
<li><p>Multicollinearity inflates the standard errors of the coefficients, making them less reliable.</p></li>
<li><p>While the model fit is high, the individual significance of predictors may be distorted due to overlapping variance.</p></li>
</ul>
</section>
</section>
<section id="autocorrelation-diagnostics" class="level2">
<h2 class="anchored" data-anchor-id="autocorrelation-diagnostics"><strong>Autocorrelation Diagnostics</strong></h2>
<p>Check if residuals are autocorrelated, because this can affect model accuracy.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb79"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb79-1"><a href="#cb79-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Durbin-Watson test for autocorrelation</span></span>
<span id="cb79-2"><a href="#cb79-2" aria-hidden="true" tabindex="-1"></a><span class="fu">durbinWatsonTest</span>(lm_fefam_multi, <span class="at">max.lag =</span> <span class="dv">2</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code> lag Autocorrelation D-W Statistic p-value
   1       0.4351862     0.9606441   0.000
   2      -0.1830626     2.1811750   0.868
 Alternative hypothesis: rho[lag] != 0</code></pre>
</div>
</div>
<section id="durbin-watson-test" class="level4">
<h4 class="anchored" data-anchor-id="durbin-watson-test"><strong>Durbin-Watson Test:</strong></h4>
<ul>
<li><p><strong>Lag 1</strong>: Autocorrelation is <strong>positive</strong> (<code>0.435</code>), and the <strong>D-W statistic = 0.96</strong> with a <strong>p-value = 0.002</strong>.</p>
<ul>
<li>This is significant evidence of <strong>positive autocorrelation</strong> in the residuals at lag 1.</li>
</ul></li>
<li><p><strong>Lag 2</strong>: The autocorrelation weakens, and the <strong>D-W statistic = 2.18</strong> with a <strong>p-value = 0.906</strong>.</p>
<ul>
<li>At lag 2, there is no significant autocorrelation.</li>
</ul></li>
</ul>
</section>
<section id="summary-of-findings" class="level3">
<h3 class="anchored" data-anchor-id="summary-of-findings"><strong>Summary of Findings</strong></h3>
<ul>
<li><p><strong>Average education</strong> (<code>avg_educ</code>), <strong>spirituality</strong> (<code>avg_spiritual</code>), and <strong>year</strong> significantly impact <code>fefam_pct</code> negatively.</p></li>
<li><p><strong>Multicollinearity</strong> exists (VIF &gt; 5), particularly with <code>avg_happy</code> and <code>year</code>.</p></li>
<li><p><strong>Positive autocorrelation</strong> at lag 1 (Durbin-Watson statistic = 0.96) violates model assumptions.</p></li>
</ul>
</section>
</section>
</section>
<section id="question-6-run-a-first-differenced-time-series-regression.-interpret-that." class="level1">
<h1>Question 6: ​​Run​​ a​​ first​​ differenced ​​time​​ series ​​regression.​​​​ Interpret​ ​that.</h1>
<section id="define-the-first-difference-function" class="level2">
<h2 class="anchored" data-anchor-id="define-the-first-difference-function"><strong>1. Define the First Difference Function</strong></h2>
<div class="cell">
<div class="sourceCode cell-code" id="cb81"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb81-1"><a href="#cb81-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Define the first difference function</span></span>
<span id="cb81-2"><a href="#cb81-2" aria-hidden="true" tabindex="-1"></a>firstD <span class="ot">&lt;-</span> <span class="cf">function</span>(var, group, df){</span>
<span id="cb81-3"><a href="#cb81-3" aria-hidden="true" tabindex="-1"></a>  bad <span class="ot">&lt;-</span> (<span class="fu">missing</span>(group) <span class="sc">&amp;</span> <span class="sc">!</span><span class="fu">missing</span>(df))</span>
<span id="cb81-4"><a href="#cb81-4" aria-hidden="true" tabindex="-1"></a>  <span class="cf">if</span> (bad) <span class="fu">stop</span>(<span class="st">"if df is specified then group must also be specified"</span>)</span>
<span id="cb81-5"><a href="#cb81-5" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb81-6"><a href="#cb81-6" aria-hidden="true" tabindex="-1"></a>  fD <span class="ot">&lt;-</span> <span class="cf">function</span>(j){ <span class="fu">c</span>(<span class="cn">NA</span>, <span class="fu">diff</span>(j)) } <span class="co"># First difference calculation</span></span>
<span id="cb81-7"><a href="#cb81-7" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb81-8"><a href="#cb81-8" aria-hidden="true" tabindex="-1"></a>  var.is.alone <span class="ot">&lt;-</span> <span class="fu">missing</span>(group) <span class="sc">&amp;</span> <span class="fu">missing</span>(df)</span>
<span id="cb81-9"><a href="#cb81-9" aria-hidden="true" tabindex="-1"></a>  <span class="cf">if</span> (var.is.alone) {</span>
<span id="cb81-10"><a href="#cb81-10" aria-hidden="true" tabindex="-1"></a>    <span class="fu">return</span>(<span class="fu">fD</span>(var))</span>
<span id="cb81-11"><a href="#cb81-11" aria-hidden="true" tabindex="-1"></a>  }</span>
<span id="cb81-12"><a href="#cb81-12" aria-hidden="true" tabindex="-1"></a>  <span class="cf">if</span> (<span class="fu">missing</span>(df)){</span>
<span id="cb81-13"><a href="#cb81-13" aria-hidden="true" tabindex="-1"></a>    V <span class="ot">&lt;-</span> var</span>
<span id="cb81-14"><a href="#cb81-14" aria-hidden="true" tabindex="-1"></a>    G <span class="ot">&lt;-</span> group</span>
<span id="cb81-15"><a href="#cb81-15" aria-hidden="true" tabindex="-1"></a>  }</span>
<span id="cb81-16"><a href="#cb81-16" aria-hidden="true" tabindex="-1"></a>  <span class="cf">else</span>{</span>
<span id="cb81-17"><a href="#cb81-17" aria-hidden="true" tabindex="-1"></a>    V <span class="ot">&lt;-</span> df[, <span class="fu">deparse</span>(<span class="fu">substitute</span>(var))]</span>
<span id="cb81-18"><a href="#cb81-18" aria-hidden="true" tabindex="-1"></a>    G <span class="ot">&lt;-</span> df[, <span class="fu">deparse</span>(<span class="fu">substitute</span>(group))]</span>
<span id="cb81-19"><a href="#cb81-19" aria-hidden="true" tabindex="-1"></a>  }</span>
<span id="cb81-20"><a href="#cb81-20" aria-hidden="true" tabindex="-1"></a>  G <span class="ot">&lt;-</span> <span class="fu">list</span>(G)</span>
<span id="cb81-21"><a href="#cb81-21" aria-hidden="true" tabindex="-1"></a>  D.var <span class="ot">&lt;-</span> <span class="fu">by</span>(V, G, fD)</span>
<span id="cb81-22"><a href="#cb81-22" aria-hidden="true" tabindex="-1"></a>  <span class="fu">unlist</span>(D.var)</span>
<span id="cb81-23"><a href="#cb81-23" aria-hidden="true" tabindex="-1"></a>}</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="create-first-differenced-data" class="level2">
<h2 class="anchored" data-anchor-id="create-first-differenced-data"><strong>2. Create First-Differenced Data</strong></h2>
<div class="cell">
<div class="sourceCode cell-code" id="cb82"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb82-1"><a href="#cb82-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(dplyr)</span>
<span id="cb82-2"><a href="#cb82-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb82-3"><a href="#cb82-3" aria-hidden="true" tabindex="-1"></a><span class="co"># Use the first differences for selected variables</span></span>
<span id="cb82-4"><a href="#cb82-4" aria-hidden="true" tabindex="-1"></a>by_year_fd <span class="ot">&lt;-</span> <span class="fu">summarise</span>(<span class="fu">data.frame</span>(by_year_interp),</span>
<span id="cb82-5"><a href="#cb82-5" aria-hidden="true" tabindex="-1"></a>                       <span class="at">fefam_pct =</span> <span class="fu">firstD</span>(fefam_pct),</span>
<span id="cb82-6"><a href="#cb82-6" aria-hidden="true" tabindex="-1"></a>                       <span class="at">avg_educ =</span> <span class="fu">firstD</span>(avg_educ),</span>
<span id="cb82-7"><a href="#cb82-7" aria-hidden="true" tabindex="-1"></a>                       <span class="at">avg_happy =</span> <span class="fu">firstD</span>(avg_happy),</span>
<span id="cb82-8"><a href="#cb82-8" aria-hidden="true" tabindex="-1"></a>                       <span class="at">avg_spiritual =</span> <span class="fu">firstD</span>(avg_spiritual),</span>
<span id="cb82-9"><a href="#cb82-9" aria-hidden="true" tabindex="-1"></a>                       <span class="at">year =</span> year)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: Returning more (or less) than 1 row per `summarise()` group was deprecated in
dplyr 1.1.0.
ℹ Please use `reframe()` instead.
ℹ When switching from `summarise()` to `reframe()`, remember that `reframe()`
  always returns an ungrouped data frame and adjust accordingly.</code></pre>
</div>
</div>
</section>
<section id="run-the-first-differenced-regression" class="level2">
<h2 class="anchored" data-anchor-id="run-the-first-differenced-regression"><strong>3. Run the First-Differenced Regression</strong></h2>
<p>The regression model <strong><code>Δfefam_pct ~ Δavg_educ + Δavg_happy + Δavg_spiritual</code></strong> examines how changes in predictors (first differences) relate to changes in <code>fefam_pct</code> over time. Here’s a detailed breakdown:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb84"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb84-1"><a href="#cb84-1" aria-hidden="true" tabindex="-1"></a><span class="co"># First differenced regression</span></span>
<span id="cb84-2"><a href="#cb84-2" aria-hidden="true" tabindex="-1"></a>lm_fefam_fd <span class="ot">&lt;-</span> <span class="fu">lm</span>(fefam_pct <span class="sc">~</span> avg_educ <span class="sc">+</span> avg_happy <span class="sc">+</span> avg_spiritual, <span class="at">data =</span> by_year_fd)</span>
<span id="cb84-3"><a href="#cb84-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb84-4"><a href="#cb84-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Summary of the model</span></span>
<span id="cb84-5"><a href="#cb84-5" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(lm_fefam_fd)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = fefam_pct ~ avg_educ + avg_happy + avg_spiritual, 
    data = by_year_fd)

Residuals:
     Min       1Q   Median       3Q      Max 
-0.65135 -0.08420  0.00189  0.07860  0.56547 

Coefficients:
              Estimate Std. Error t value Pr(&gt;|t|)   
(Intercept)    -0.2597     0.1316  -1.973   0.0661 . 
avg_educ       -2.2343     0.6206  -3.600   0.0024 **
avg_happy     -10.1496    12.3839  -0.820   0.4245   
avg_spiritual -10.5133     4.6522  -2.260   0.0381 * 
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 0.3303 on 16 degrees of freedom
  (31 observations deleted due to missingness)
Multiple R-squared:  0.5203,    Adjusted R-squared:  0.4303 
F-statistic: 5.784 on 3 and 16 DF,  p-value: 0.007088</code></pre>
</div>
</div>
<ul>
<li><p><strong>Intercept</strong>: <code>-0.2597</code></p>
<ul>
<li>The intercept is not significant (<code>p = 0.0661</code>), which means the average change in <code>fefam_pct</code> when all predictors’ changes are zero is not distinguishable from zero.</li>
</ul></li>
<li><p><strong><code>avg_educ</code> (-2.2343, p = 0.0024)</strong>:</p>
<ul>
<li><p>A <strong>one-unit increase</strong> in the <strong>change</strong> of average education (<code>Δavg_educ</code>) is associated with a <strong>2.23 percentage point decrease</strong> in the <strong>change</strong> of <code>fefam_pct</code>.</p></li>
<li><p>This is statistically significant at the <strong>1% level</strong> (<strong>p &lt; 0.01</strong>).</p></li>
<li><p>Interpretation: As education levels increase over time, support for traditional family roles decreases significantly.</p></li>
</ul></li>
<li><p><strong><code>avg_happy</code> (-10.1496, p = 0.4245)</strong>:</p>
<ul>
<li><p>The coefficient is negative, suggesting that an increase in <strong>average happiness</strong> might reduce <code>fefam_pct</code>, but it is <strong>not statistically significant</strong> (<code>p = 0.4245</code>).</p></li>
<li><p>Interpretation: Changes in happiness levels do not have a clear relationship with changes in <code>fefam_pct</code>.</p></li>
</ul></li>
<li><p><strong><code>avg_spiritual</code> (-10.5133, p = 0.0381)</strong>:</p>
<ul>
<li><p>A <strong>one-unit increase</strong> in the <strong>change</strong> of spirituality (<code>Δavg_spiritual</code>) is associated with a <strong>10.51 percentage point decrease</strong> in <code>Δfefam_pct</code>.</p></li>
<li><p>This is statistically significant at the <strong>5% level</strong> (<strong>p &lt; 0.05</strong>).</p></li>
<li><p>Interpretation: A rising trend in spirituality correlates with a significant decrease in support for traditional family roles.</p></li>
</ul></li>
</ul>
<section id="model-fit-1" class="level3">
<h3 class="anchored" data-anchor-id="model-fit-1"><strong>Model Fit</strong></h3>
<ul>
<li><p><strong>R-squared = 0.5203</strong>:</p>
<ul>
<li><p>About <strong>52% of the variation</strong> in the change of <code>fefam_pct</code> is explained by changes in <code>avg_educ</code>, <code>avg_happy</code>, and <code>avg_spiritual</code>.</p></li>
<li><p>This is decent, especially given that differencing removes much of the trend in the data.</p></li>
</ul></li>
<li><p><strong>Adjusted R-squared = 0.4303</strong>:</p>
<ul>
<li>After adjusting for the number of predictors, the model still explains about <strong>43%</strong> of the variation.</li>
</ul></li>
<li><p><strong>F-statistic = 5.784, p-value = 0.0071</strong>:</p>
<ul>
<li>The overall model is statistically significant, indicating that at least one predictor significantly explains changes in <code>fefam_pct</code>.</li>
</ul></li>
</ul>
</section>
</section>
<section id="check-residuals-for-autocorrelation" class="level2">
<h2 class="anchored" data-anchor-id="check-residuals-for-autocorrelation"><strong>4. Check Residuals for Autocorrelation</strong></h2>
<div class="cell">
<div class="sourceCode cell-code" id="cb86"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb86-1"><a href="#cb86-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Extract residuals</span></span>
<span id="cb86-2"><a href="#cb86-2" aria-hidden="true" tabindex="-1"></a>e_fd <span class="ot">&lt;-</span> lm_fefam_fd<span class="sc">$</span>residuals</span>
<span id="cb86-3"><a href="#cb86-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb86-4"><a href="#cb86-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Plot ACF and PACF of residuals</span></span>
<span id="cb86-5"><a href="#cb86-5" aria-hidden="true" tabindex="-1"></a><span class="fu">acf</span>(e_fd, <span class="at">main =</span> <span class="st">"ACF of Residuals (First Differenced)"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="ARIMA_files/figure-html/unnamed-chunk-22-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="sourceCode cell-code" id="cb87"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb87-1"><a href="#cb87-1" aria-hidden="true" tabindex="-1"></a><span class="fu">pacf</span>(e_fd, <span class="at">main =</span> <span class="st">"PACF of Residuals (First Differenced)"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="ARIMA_files/figure-html/unnamed-chunk-22-2.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="sourceCode cell-code" id="cb88"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb88-1"><a href="#cb88-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Install and load 'forecast' for auto.arima</span></span>
<span id="cb88-2"><a href="#cb88-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(forecast)</span>
<span id="cb88-3"><a href="#cb88-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb88-4"><a href="#cb88-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Test residuals for ARIMA structure</span></span>
<span id="cb88-5"><a href="#cb88-5" aria-hidden="true" tabindex="-1"></a><span class="fu">auto.arima</span>(e_fd, <span class="at">trace =</span> <span class="cn">TRUE</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
 ARIMA(2,0,2) with non-zero mean : Inf
 ARIMA(0,0,0) with non-zero mean : 12.68829
 ARIMA(1,0,0) with non-zero mean : 14.80955
 ARIMA(0,0,1) with non-zero mean : Inf
 ARIMA(0,0,0) with zero mean     : 10.20463
 ARIMA(1,0,1) with non-zero mean : Inf

 Best model: ARIMA(0,0,0) with zero mean     </code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>Series: e_fd 
ARIMA(0,0,0) with zero mean 

sigma^2 = 0.08727:  log likelihood = -3.99
AIC=9.98   AICc=10.2   BIC=10.98</code></pre>
</div>
</div>
<section id="acf-plot-of-residuals" class="level3">
<h3 class="anchored" data-anchor-id="acf-plot-of-residuals"><strong>1. ACF Plot of Residuals</strong></h3>
<ul>
<li><p><strong>What It Shows</strong>:</p>
<ul>
<li><p>The <strong>Autocorrelation Function (ACF)</strong> measures the correlation of residuals at various lags.</p></li>
<li><p>Ideally, for well-behaved residuals, the ACF should show <strong>no significant spikes</strong>, meaning the residuals are uncorrelated and resemble white noise.</p></li>
</ul></li>
<li><p><strong>What We See</strong>:</p>
<ul>
<li><p>At <strong>lag 1</strong>, there is a significant spike (above the blue dashed line), indicating <strong>positive autocorrelation</strong>.</p></li>
<li><p>Subsequent lags show much smaller spikes, suggesting that the autocorrelation diminishes quickly.</p></li>
</ul></li>
<li><p><strong>Conclusion</strong>:</p>
<ul>
<li>The residuals still have some <strong>remaining autocorrelation</strong> at lag 1, which suggests the model hasn’t fully accounted for all time dependencies.</li>
</ul></li>
</ul>
</section>
<section id="pacf-plot-of-residuals" class="level3">
<h3 class="anchored" data-anchor-id="pacf-plot-of-residuals"><strong>2. PACF Plot of Residuals</strong></h3>
<ul>
<li><p><strong>What It Shows</strong>:</p>
<ul>
<li><p>The <strong>Partial Autocorrelation Function (PACF)</strong> measures the correlation between residuals at a given lag, accounting for the effects of intermediate lags.</p></li>
<li><p>Significant spikes indicate which lags contribute most to the autocorrelation.</p></li>
</ul></li>
<li><p><strong>What We See</strong>:</p>
<ul>
<li>There are notable spikes at <strong>lag 1</strong> and <strong>lag 3</strong>, suggesting that the autocorrelation at lag 1 and lag 3 is significant.</li>
</ul></li>
<li><p><strong>Conclusion</strong>:</p>
<ul>
<li><p>This confirms the ACF findings: residual autocorrelation remains at lag 1 and potentially lag 3.</p></li>
<li><p>The residuals are not yet fully white noise.</p></li>
</ul></li>
</ul>
</section>
<section id="arima-results" class="level3">
<h3 class="anchored" data-anchor-id="arima-results"><strong>3. ARIMA Results</strong></h3>
<p>my ARIMA analysis applied to the residuals identified the <strong>best model</strong> as <strong>ARIMA(0,0,0) with zero mean</strong>. This is essentially a model where the residuals are <strong>white noise</strong> (i.e., no further structure or autocorrelation is detected).</p>
<section id="why-arima000" class="level4">
<h4 class="anchored" data-anchor-id="why-arima000"><strong>Why ARIMA(0,0,0)?</strong></h4>
<ul>
<li><p>ARIMA(0,0,0) with zero mean indicates that the residuals are sufficiently random, with no further time-dependent patterns that need modeling.</p></li>
<li><p><strong>sigma^2 = 0.08727</strong>: The estimated variance of the residuals is small.</p></li>
<li><p><strong>AIC = 9.98</strong>: This is the lowest AIC score among tested models, confirming it as the best fit.</p></li>
</ul>
</section>
</section>
<section id="what-it-all-means" class="level3">
<h3 class="anchored" data-anchor-id="what-it-all-means"><strong>What It All Means</strong></h3>
<ol type="1">
<li><p><strong>ACF and PACF</strong>: There is slight autocorrelation remaining in the residuals (lag 1 and lag 3).</p></li>
<li><p><strong>ARIMA(0,0,0)</strong>: Despite small spikes in ACF/PACF, the residuals appear sufficiently white noise for modeling purposes.</p></li>
<li><p><strong>Model Diagnosis</strong>:</p>
<ul>
<li><p>my first-differenced regression has addressed most of the autocorrelation, but minor residual patterns remain.</p></li>
<li><p>For better precision, you could explore including lagged variables (e.g., lag 1 of predictors or response).</p></li>
</ul></li>
</ol>
</section>
</section>
</section>
<section id="question-7-check-your-variables-for-unit-roots.-do-some-tests.-interpret-them." class="level1">
<h1>Question 7: Check​​ your ​​variables ​​for​​ unit ​​roots.​​​​ Do​​ some ​​tests.​​​​ Interpret​ ​them.​​​​</h1>
<section id="adf-test" class="level2">
<h2 class="anchored" data-anchor-id="adf-test">ADF Test</h2>
<div class="cell">
<div class="sourceCode cell-code" id="cb91"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb91-1"><a href="#cb91-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Load the required library</span></span>
<span id="cb91-2"><a href="#cb91-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(fUnitRoots)</span>
<span id="cb91-3"><a href="#cb91-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb91-4"><a href="#cb91-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Run ADF test on fefam_pct with a constant and trend</span></span>
<span id="cb91-5"><a href="#cb91-5" aria-hidden="true" tabindex="-1"></a><span class="fu">adfTest</span>(by_year_interp<span class="sc">$</span>fefam_pct, <span class="at">lags =</span> <span class="dv">0</span>, <span class="at">type =</span> <span class="st">"ct"</span>)  <span class="co"># No lags</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Title:
 Augmented Dickey-Fuller Test

Test Results:
  PARAMETER:
    Lag Order: 0
  STATISTIC:
    Dickey-Fuller: -2.7346
  P VALUE:
    0.2791 

Description:
 Tue Dec 17 17:51:41 2024 by user: nmv2125</code></pre>
</div>
<div class="sourceCode cell-code" id="cb93"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb93-1"><a href="#cb93-1" aria-hidden="true" tabindex="-1"></a><span class="fu">adfTest</span>(by_year_interp<span class="sc">$</span>fefam_pct, <span class="at">lags =</span> <span class="dv">4</span>, <span class="at">type =</span> <span class="st">"ct"</span>)  <span class="co"># With lags</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Title:
 Augmented Dickey-Fuller Test

Test Results:
  PARAMETER:
    Lag Order: 4
  STATISTIC:
    Dickey-Fuller: -2.6455
  P VALUE:
    0.3149 

Description:
 Tue Dec 17 17:51:41 2024 by user: nmv2125</code></pre>
</div>
</div>
<ul>
<li><p><strong>Lag 0:</strong></p>
<ul>
<li><p><strong>Dickey-Fuller statistic</strong>: <code>-2.7346</code></p></li>
<li><p><strong>p-value</strong>: <code>0.2791</code></p></li>
</ul></li>
<li><p><strong>Lag 4:</strong></p>
<ul>
<li><p><strong>Dickey-Fuller statistic</strong>: <code>-2.6455</code></p></li>
<li><p><strong>p-value</strong>: <code>0.3149</code></p></li>
</ul></li>
</ul>
<section id="interpretation-of-adf-results" class="level4">
<h4 class="anchored" data-anchor-id="interpretation-of-adf-results"><strong>Interpretation of ADF Results:</strong></h4>
<ul>
<li><p>The <strong>null hypothesis</strong> of the ADF test is that the series has a <strong>unit root</strong> (non-stationary).</p></li>
<li><p>Since the <strong>p-values &gt; 0.05</strong> for both tests, you <strong>fail to reject the null hypothesis</strong>.</p></li>
<li><p>Conclusion: The series <code>fefam_pct</code> <strong>has a unit root</strong> and is <strong>non-stationary</strong>.</p></li>
</ul>
</section>
</section>
<section id="phillips-perron-test" class="level2">
<h2 class="anchored" data-anchor-id="phillips-perron-test">Phillips-Perron Test</h2>
<div class="cell">
<div class="sourceCode cell-code" id="cb95"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb95-1"><a href="#cb95-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Load the tseries package for Phillips-Perron test</span></span>
<span id="cb95-2"><a href="#cb95-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tseries)</span>
<span id="cb95-3"><a href="#cb95-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb95-4"><a href="#cb95-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Run the PP test</span></span>
<span id="cb95-5"><a href="#cb95-5" aria-hidden="true" tabindex="-1"></a><span class="fu">PP.test</span>(by_year_interp<span class="sc">$</span>fefam_pct, <span class="at">lshort =</span> <span class="cn">TRUE</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Phillips-Perron Unit Root Test

data:  by_year_interp$fefam_pct
Dickey-Fuller = NA, Truncation lag parameter = 3, p-value = NA</code></pre>
</div>
</div>
</section>
</section>
<section id="question-8-performan-automatic-arima-on-the-residuals-from-one-of-your-earlier-models.-tell-me-what-it-says." class="level1">
<h1>Question 8: ​Perform​​an​​ Automatic​​ ARIMA ​​on​​ the ​​residuals​​ from​​ one​​ of​​ your ​​earlier​​ models.​​​​ Tell​​ me​​ what​​ it​​ says.</h1>
<div class="cell">
<div class="sourceCode cell-code" id="cb97"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb97-1"><a href="#cb97-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Extract residuals from the first-differenced regression</span></span>
<span id="cb97-2"><a href="#cb97-2" aria-hidden="true" tabindex="-1"></a>resid_fd <span class="ot">&lt;-</span> lm_fefam_fd<span class="sc">$</span>residuals</span>
<span id="cb97-3"><a href="#cb97-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb97-4"><a href="#cb97-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Load the forecast package</span></span>
<span id="cb97-5"><a href="#cb97-5" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(forecast)</span>
<span id="cb97-6"><a href="#cb97-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb97-7"><a href="#cb97-7" aria-hidden="true" tabindex="-1"></a><span class="co"># Perform Automatic ARIMA on residuals</span></span>
<span id="cb97-8"><a href="#cb97-8" aria-hidden="true" tabindex="-1"></a>auto_arima_resid <span class="ot">&lt;-</span> <span class="fu">auto.arima</span>(resid_fd, <span class="at">trace =</span> <span class="cn">TRUE</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
 ARIMA(2,0,2) with non-zero mean : Inf
 ARIMA(0,0,0) with non-zero mean : 12.68829
 ARIMA(1,0,0) with non-zero mean : 14.80955
 ARIMA(0,0,1) with non-zero mean : Inf
 ARIMA(0,0,0) with zero mean     : 10.20463
 ARIMA(1,0,1) with non-zero mean : Inf

 Best model: ARIMA(0,0,0) with zero mean     </code></pre>
</div>
<div class="sourceCode cell-code" id="cb99"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb99-1"><a href="#cb99-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Print the model summary</span></span>
<span id="cb99-2"><a href="#cb99-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(auto_arima_resid)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Series: resid_fd 
ARIMA(0,0,0) with zero mean 

sigma^2 = 0.08727:  log likelihood = -3.99
AIC=9.98   AICc=10.2   BIC=10.98

Training set error measures:
                      ME      RMSE       MAE MPE MAPE     MASE      ACF1
Training set 5.20417e-18 0.2954138 0.1935998 100  100 1.011638 0.1787835</code></pre>
</div>
</div>
<p>The <strong>best ARIMA model</strong> selected by <code>auto.arima()</code> for my residuals is <strong>ARIMA(0,0,0) with zero mean</strong>.</p>
<section id="model-explanation" class="level3">
<h3 class="anchored" data-anchor-id="model-explanation"><strong>1. Model Explanation</strong></h3>
<ul>
<li><p><strong>ARIMA(0,0,0)</strong>:</p>
<ul>
<li><p>No autoregressive terms (AR = 0), no differencing (D = 0), and no moving average terms (MA = 0).</p></li>
<li><p>This model states that the residuals are <strong>white noise</strong>, meaning there is no remaining time dependency or structure in them.</p></li>
</ul></li>
<li><p><strong>Zero Mean</strong>:</p>
<ul>
<li>The model assumes the mean of the residuals is zero.</li>
</ul></li>
</ul>
</section>
<section id="model-diagnostics" class="level3">
<h3 class="anchored" data-anchor-id="model-diagnostics"><strong>2. Model Diagnostics</strong></h3>
<ul>
<li><p><strong><code>sigma^2 = 0.08727</code></strong>:</p>
<ul>
<li>The variance of the residuals is low, indicating the residuals are tightly distributed around zero.</li>
</ul></li>
<li><p><strong>Log Likelihood = -3.99</strong>:</p>
<ul>
<li>A measure of model fit; the closer to zero, the better.</li>
</ul></li>
<li><p><strong>AIC (9.98), AICc (10.2), and BIC (10.98)</strong>:</p>
<ul>
<li>These criteria confirm that ARIMA(0,0,0) is the best-fitting model among the tested options. Lower values suggest better model performance.</li>
</ul></li>
</ul>
</section>
<section id="error-measures" class="level3">
<h3 class="anchored" data-anchor-id="error-measures"><strong>3. Error Measures</strong></h3>
<ul>
<li><p><strong>ME (Mean Error)</strong>: Close to zero (<code>5.20417e-18</code>), indicating no bias in the residuals.</p></li>
<li><p><strong>RMSE (Root Mean Squared Error) = 0.2954</strong>: A small value, showing low error in the residuals.</p></li>
<li><p><strong>MAE (Mean Absolute Error) = 0.1936</strong>: Small average absolute deviation.</p></li>
<li><p><strong>ACF1 = 0.1788</strong>: The autocorrelation at lag 1 is small but not completely negligible.</p></li>
</ul>
</section>
<section id="conclusion" class="level3">
<h3 class="anchored" data-anchor-id="conclusion"><strong>4. Conclusion</strong></h3>
<p>The ARIMA(0,0,0) with zero mean confirms that:</p>
<ul>
<li><p>The residuals from my regression are effectively <strong>white noise</strong>.</p></li>
<li><p>This means the original regression model captured all meaningful time series structure in the data.</p></li>
<li><p>There’s no need for further modeling or adjustments to the residuals.</p></li>
</ul>
</section>
<section id="what-this-means-for-my-analysis" class="level3">
<h3 class="anchored" data-anchor-id="what-this-means-for-my-analysis"><strong>What This Means for My Analysis</strong></h3>
<ul>
<li><p>The regression model is well-specified and does not exhibit significant autocorrelation or time-dependent patterns in the residuals.</p></li>
<li><p>I can confidently conclude that my earlier model is adequate.</p></li>
</ul>
</section>
</section>
<section id="question-9-run-an-arima-that-follows-from-step-8.-interpret-that-too." class="level1">
<h1>Question 9: ​​Run​​ an​​ ARIMA​​ that​ ​follows ​​from ​​Step​​ 8.​​​​ Interpret​​ that,​​ too.</h1>
<div class="cell">
<div class="sourceCode cell-code" id="cb101"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb101-1"><a href="#cb101-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Define external regressors</span></span>
<span id="cb101-2"><a href="#cb101-2" aria-hidden="true" tabindex="-1"></a>xvars <span class="ot">&lt;-</span> by_year_interp[, <span class="fu">c</span>(<span class="st">"avg_educ"</span>, <span class="st">"avg_happy"</span>, <span class="st">"avg_spiritual"</span>)]</span>
<span id="cb101-3"><a href="#cb101-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb101-4"><a href="#cb101-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Run ARIMA(0,0,0) with external regressors</span></span>
<span id="cb101-5"><a href="#cb101-5" aria-hidden="true" tabindex="-1"></a>arima_xreg <span class="ot">&lt;-</span> <span class="fu">arima</span>(by_year_interp<span class="sc">$</span>fefam_pct, <span class="at">order =</span> <span class="fu">c</span>(<span class="dv">0</span>,<span class="dv">0</span>,<span class="dv">0</span>), <span class="at">xreg =</span> xvars)</span>
<span id="cb101-6"><a href="#cb101-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb101-7"><a href="#cb101-7" aria-hidden="true" tabindex="-1"></a><span class="co"># Summary of the ARIMA model</span></span>
<span id="cb101-8"><a href="#cb101-8" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(arima_xreg)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
arima(x = by_year_interp$fefam_pct, order = c(0, 0, 0), xreg = xvars)

Coefficients:
      intercept  avg_educ  avg_happy  avg_spiritual
       -11.1517   -3.3062    23.7273       -23.2602
s.e.    45.5697    1.1168     4.8161         5.7590

sigma^2 estimated as 0.3644:  log likelihood = -19.2,  aic = 48.4

Training set error measures:
                       ME      RMSE       MAE        MPE     MAPE      MASE
Training set 8.289668e-14 0.6036443 0.4818594 -0.5790272 6.513527 0.7269473
                  ACF1
Training set 0.7793751</code></pre>
</div>
</div>
<section id="coefficients" class="level4">
<h4 class="anchored" data-anchor-id="coefficients"><strong>Coefficients</strong>:</h4>
<ul>
<li><p><strong>Intercept</strong>: <code>-11.1517</code> (standard error = <code>45.5697</code>):</p>
<ul>
<li>The intercept is not significant given the large standard error, which suggests it may not contribute meaningfully to the model.</li>
</ul></li>
<li><p><strong><code>avg_educ</code> (-3.3062, s.e. = 1.1168)</strong>:</p>
<ul>
<li><p><strong>Negative and significant</strong>: A unit increase in <code>avg_educ</code> decreases <code>fefam_pct</code> by approximately <strong>3.31 percentage points</strong>.</p></li>
<li><p>The relatively small standard error confirms its precision.</p></li>
</ul></li>
<li><p><strong><code>avg_happy</code> (23.7273, s.e. = 4.8161)</strong>:</p>
<ul>
<li><p><strong>Positive and significant</strong>: A unit increase in <code>avg_happy</code> increases <code>fefam_pct</code> by approximately <strong>23.73 percentage points</strong>.</p></li>
<li><p>This effect is large and precise (small standard error).</p></li>
</ul></li>
<li><p><strong><code>avg_spiritual</code> (-23.2602, s.e. = 5.7590)</strong>:</p>
<ul>
<li><p><strong>Negative and significant</strong>: A unit increase in <code>avg_spiritual</code> decreases <code>fefam_pct</code> by approximately <strong>23.26 percentage points</strong>.</p></li>
<li><p>This is also a strong effect, supported by a relatively low standard error.</p></li>
</ul></li>
</ul>
</section>
<section id="model-fit-2" class="level4">
<h4 class="anchored" data-anchor-id="model-fit-2"><strong>Model Fit</strong>:</h4>
<ul>
<li><p><strong><code>sigma^2 = 0.3644</code></strong>: Residual variance is moderate, suggesting the model fits the data reasonably well.</p></li>
<li><p><strong>Log Likelihood = -19.2</strong> and <strong>AIC = 48.4</strong>:</p>
<ul>
<li>Lower AIC indicates a better-fitting model compared to alternatives.</li>
</ul></li>
</ul>
</section>
<section id="training-set-error-measures" class="level3">
<h3 class="anchored" data-anchor-id="training-set-error-measures"><strong>2. Training Set Error Measures</strong>:</h3>
<ul>
<li><p><strong>ME (Mean Error) ≈ 0</strong>: Residuals are unbiased on average.</p></li>
<li><p><strong>RMSE = 0.6036</strong> and <strong>MAE = 0.4819</strong>:</p>
<ul>
<li>The errors are relatively small, indicating good predictive accuracy.</li>
</ul></li>
<li><p><strong>MAPE = 6.51%</strong>: The model has a mean absolute percentage error of ~6.5%, which is acceptable.</p></li>
<li><p><strong>ACF1 = 0.779</strong>: The autocorrelation of residuals at lag 1 is quite high, suggesting residual autocorrelation remains.</p></li>
</ul>
</section>
<section id="check-for-residual-autocorrelation" class="level2">
<h2 class="anchored" data-anchor-id="check-for-residual-autocorrelation">Check for Residual Autocorrelation</h2>
<div class="cell">
<div class="sourceCode cell-code" id="cb103"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb103-1"><a href="#cb103-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Perform Ljung-Box test on residuals</span></span>
<span id="cb103-2"><a href="#cb103-2" aria-hidden="true" tabindex="-1"></a><span class="fu">Box.test</span>(<span class="fu">resid</span>(arima_xreg), <span class="at">lag =</span> <span class="dv">20</span>, <span class="at">type =</span> <span class="st">"Ljung-Box"</span>, <span class="at">fitdf =</span> <span class="dv">0</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Box-Ljung test

data:  resid(arima_xreg)
X-squared = 56.434, df = 20, p-value = 2.5e-05</code></pre>
</div>
</div>
<section id="interpretation-1" class="level4">
<h4 class="anchored" data-anchor-id="interpretation-1"><strong>Interpretation</strong>:</h4>
<ul>
<li><p><strong>Null Hypothesis</strong>: Residuals are white noise (no autocorrelation).</p></li>
<li><p><strong>p-value = 2.5e-05 (&lt; 0.05)</strong>: The null hypothesis is rejected.</p>
<ul>
<li><p>This indicates <strong>significant autocorrelation</strong> remains in the residuals.</p></li>
<li><p>The model does not fully capture all time-dependent patterns.</p></li>
</ul></li>
</ul>
</section>
<section id="summary" class="level3">
<h3 class="anchored" data-anchor-id="summary"><strong>Summary</strong></h3>
<ul>
<li><p>The model explains the effects of predictors well:</p>
<ul>
<li><p><code>avg_educ</code> and <code>avg_spiritual</code> have significant negative effects on <code>fefam_pct</code>.</p></li>
<li><p><code>avg_happy</code> has a significant positive effect.</p></li>
</ul></li>
<li><p>However, residual diagnostics (Box-Ljung test and ACF1) show <strong>remaining autocorrelation</strong>, suggesting that the model could be improved further.</p></li>
</ul>
</section>
</section>
</section>

</main>
<!-- /main column -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const onCopySuccess = function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  }
  const getTextToCopy = function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
    text: getTextToCopy
  });
  clipboard.on('success', onCopySuccess);
  if (window.document.getElementById('quarto-embedded-source-code-modal')) {
    // For code content inside modals, clipBoardJS needs to be initialized with a container option
    // TODO: Check when it could be a function (https://github.com/zenorocha/clipboard.js/issues/860)
    const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
      text: getTextToCopy,
      container: window.document.getElementById('quarto-embedded-source-code-modal')
    });
    clipboardModal.on('success', onCopySuccess);
  }
    var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
    var mailtoRegex = new RegExp(/^mailto:/);
      var filterRegex = new RegExp('/' + window.location.host + '/');
    var isInternal = (href) => {
        return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
    }
    // Inspect non-navigation links and adorn them if external
 	var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
    for (var i=0; i<links.length; i++) {
      const link = links[i];
      if (!isInternal(link.href)) {
        // undo the damage that might have been done by quarto-nav.js in the case of
        // links that we want to consider external
        if (link.dataset.originalHref !== undefined) {
          link.href = link.dataset.originalHref;
        }
      }
    }
  function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
    const config = {
      allowHTML: true,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start',
    };
    if (contentFn) {
      config.content = contentFn;
    }
    if (onTriggerFn) {
      config.onTrigger = onTriggerFn;
    }
    if (onUntriggerFn) {
      config.onUntrigger = onUntriggerFn;
    }
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      if (note) {
        return note.innerHTML;
      } else {
        return "";
      }
    });
  }
  const xrefs = window.document.querySelectorAll('a.quarto-xref');
  const processXRef = (id, note) => {
    // Strip column container classes
    const stripColumnClz = (el) => {
      el.classList.remove("page-full", "page-columns");
      if (el.children) {
        for (const child of el.children) {
          stripColumnClz(child);
        }
      }
    }
    stripColumnClz(note)
    if (id === null || id.startsWith('sec-')) {
      // Special case sections, only their first couple elements
      const container = document.createElement("div");
      if (note.children && note.children.length > 2) {
        container.appendChild(note.children[0].cloneNode(true));
        for (let i = 1; i < note.children.length; i++) {
          const child = note.children[i];
          if (child.tagName === "P" && child.innerText === "") {
            continue;
          } else {
            container.appendChild(child.cloneNode(true));
            break;
          }
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(container);
        }
        return container.innerHTML
      } else {
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        return note.innerHTML;
      }
    } else {
      // Remove any anchor links if they are present
      const anchorLink = note.querySelector('a.anchorjs-link');
      if (anchorLink) {
        anchorLink.remove();
      }
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(note);
      }
      // TODO in 1.5, we should make sure this works without a callout special case
      if (note.classList.contains("callout")) {
        return note.outerHTML;
      } else {
        return note.innerHTML;
      }
    }
  }
  for (var i=0; i<xrefs.length; i++) {
    const xref = xrefs[i];
    tippyHover(xref, undefined, function(instance) {
      instance.disable();
      let url = xref.getAttribute('href');
      let hash = undefined; 
      if (url.startsWith('#')) {
        hash = url;
      } else {
        try { hash = new URL(url).hash; } catch {}
      }
      if (hash) {
        const id = hash.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note !== null) {
          try {
            const html = processXRef(id, note.cloneNode(true));
            instance.setContent(html);
          } finally {
            instance.enable();
            instance.show();
          }
        } else {
          // See if we can fetch this
          fetch(url.split('#')[0])
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.getElementById(id);
            if (note !== null) {
              const html = processXRef(id, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      } else {
        // See if we can fetch a full url (with no hash to target)
        // This is a special case and we should probably do some content thinning / targeting
        fetch(url)
        .then(res => res.text())
        .then(html => {
          const parser = new DOMParser();
          const htmlDoc = parser.parseFromString(html, "text/html");
          const note = htmlDoc.querySelector('main.content');
          if (note !== null) {
            // This should only happen for chapter cross references
            // (since there is no id in the URL)
            // remove the first header
            if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
              note.children[0].remove();
            }
            const html = processXRef(null, note);
            instance.setContent(html);
          } 
        }).finally(() => {
          instance.enable();
          instance.show();
        });
      }
    }, function(instance) {
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            div.style.left = 0;
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
        // Handle positioning of the toggle
    window.addEventListener(
      "resize",
      throttle(() => {
        elRect = undefined;
        if (selectedAnnoteEl) {
          selectCodeLines(selectedAnnoteEl);
        }
      }, 10)
    );
    function throttle(fn, ms) {
    let throttle = false;
    let timer;
      return (...args) => {
        if(!throttle) { // first call gets through
            fn.apply(this, args);
            throttle = true;
        } else { // all the others get throttled
            if(timer) clearTimeout(timer); // cancel #2
            timer = setTimeout(() => {
              fn.apply(this, args);
              timer = throttle = false;
            }, ms);
        }
      };
    }
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->




</body></html>